### PR TITLE
Adds manual filtering for languages in fetch_repos

### PR DESCRIPTION
**Pull request by deepaks2112**
This PR fixes the [issue](https://github.com/hedyhli/gtrending/issues/33).

### CODE REVIEW

**Review by hedyhli — CHANGES_REQUESTED** [review]
Hey, this is looking good. Could you just uncomment the language tests:
https://github.com/hedyhli/gtrending/blob/0bb9ec90e3ce7ce36cb64368fb0f582a2bc97c96/tests/test_fetch_repos.py#L32-L36
And remove that comment on line 31 because it's fixed now, thanks :)

**Comment by deepaks2112** [comment]
Hi, I have made the changes.

**Review by hedyhli — APPROVED** [review]
Perfect, I'll run the checks and if all goes well I'll merge

**Comment by hedyhli** [comment]
I've fixed the mypy test, thanks for your contribution 🙌

**Pull request merged**
